### PR TITLE
Update green color to make it darker and add underline

### PR DESCRIPTION
**Pull request by lisasy**
Proposed design:

Screen Shot 2021-06-30 at 9 24 34 PM

The green color #005B30 on white background passes contrast ratio tests for accessibility.

### CODE REVIEW

**Review by aitchiss — COMMENTED** [review]
In the proposed design, the link underline is always visible, but in the deploy preview we can only see it on hover - should we change that as part of this PR too?

I think it looks great, but without the underline maybe it's a bit close to the normal text colour to distinguish the links - what do you think?

**Comment by FounderCasey** [comment]
Before we merge this let's also remove the second algolia info in `docusaurus.config.js`, unless @Zhao-Andy is okay with keeping this live 

Can I get a confirmation on whether or not the underline is always visible? If it's always visible, we might want to drop the weight on the links because it looks really heavy - thoughts?

**Review by FounderCasey — CHANGES_REQUESTED** [review]
Before we merge this let's also remove the second algolia info in `docusaurus.config.js`, unless @Zhao-Andy is okay with keeping them

I see that links are supposed to have the underline, we might want to drop the weight on the links because it looks really heavy - thoughts?

**Comment by lisasy** [comment]
> In the proposed design, the link underline is always visible, but in the deploy preview we can only see it on hover - should we change that as part of this PR too?
> 
> I think it looks great, but without the underline maybe it's a bit close to the normal text colour to distinguish the links - what do you think?

Very strange that in the deploy preview, it's only visible on hover :( The intent is for the underline to be visible for the default and hover state.

**Comment by lisasy** [comment]
> Before we merge this let's also remove the algolia info in `docusaurus.config.js` and replace it with the env variables, unless @Zhao-Andy is okay with keeping them
> 
> I see that links are supposed to have the underline, we might want to drop the weight on the links because it looks really heavy - thoughts?

Sounds great — let's drop the weight on the links to use `400` instead of `600`.

**Comment by aitchiss** [comment]
> Very strange that in the deploy preview, it's only visible on hover :( The intent is for the underline to be visible for the default and hover state.

I had a wee look and it looks like we have a CSS variable `--ifm-link-decoration` which is set to `none`, making the underlines invisible unless hovered. [Looks like this is some Docusaurus default](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima) that we need to overrided in the `:root` selector

**Review by FounderCasey — APPROVED** [review]
Updated these to accommodate the changes - all set now

**Pull request merged**
